apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - job.yaml

configMapGenerator:
  - name: clickhouse-migrations
    files:
      - migrations/000001_init.up.sql
      - migrations/000001_init.down.sql
