---
apiVersion: v1
kind: ConfigMap
metadata:
    name: ch-shell-config
    namespace: o11y-system
data:
    config.xml: |
        <config>
          <openSSL>
            <client>
              <certificateFile>/etc/clickhouse-client/certs/tls.crt</certificateFile>
              <privateKeyFile>/etc/clickhouse-client/certs/tls.key</privateKeyFile>
              <caConfig>/etc/clickhouse-client/certs/ca.crt</caConfig>
              <loadDefaultCAFile>true</loadDefaultCAFile>
              <verificationMode>relaxed</verificationMode>
              <invalidCertificateHandler>
                <name>RejectCertificateHandler</name>
              </invalidCertificateHandler>
            </client>
          </openSSL>
        </config>
---
apiVersion: v1
kind: Pod
metadata:
    name: ch-shell
    namespace: o11y-system
spec:
    restartPolicy: Never
    securityContext:
        fsGroup: 101
    containers:
        - name: client
          image: clickhouse/clickhouse-server:25.3-alpine
          command: ["sleep", "infinity"]
          volumeMounts:
              - name: client-certs
                mountPath: /etc/clickhouse-client/certs
                readOnly: true
              - name: client-config
                mountPath: /etc/clickhouse-client/config.xml
                subPath: config.xml
                readOnly: true
    volumes:
        - name: client-certs
          csi:
              driver: csi.cert-manager.io
              readOnly: true
              volumeAttributes:
                  csi.cert-manager.io/issuer-name: o11y-system
                  csi.cert-manager.io/issuer-kind: ClusterIssuer
                  csi.cert-manager.io/common-name: clickhouse-migrations-client
                  csi.cert-manager.io/duration: 24h
                  csi.cert-manager.io/key-usages: client auth
                  csi.cert-manager.io/fs-group: "101"
        - name: client-config
          configMap:
              name: ch-shell-config
