name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint (${{ matrix.module }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - operator
          - clickhouse-migrate
          - receiver/natsreceiver
          - exporter/natsexporter
          - processor/unbatchprocessor
          - queryapi
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ matrix.module }}/go.mod

      - name: Run linter
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.12.2
          working-directory: ${{ matrix.module }}
