name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test (${{ matrix.module }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - module: config
            test-cmd: go test ./...
          - module: operator
            test-cmd: task test
          - module: clickhouse-migrate
            test-cmd: go test ./...
          - module: receiver/natsreceiver
            test-cmd: go test ./...
          - module: exporter/natsexporter
            test-cmd: go test ./...
          - module: processor/unbatchprocessor
            test-cmd: go test ./...
          - module: queryapi
            test-cmd: task test
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ matrix.module }}/go.mod

      - name: Setup Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Running Tests
        working-directory: ${{ matrix.module }}
        run: |
          go mod tidy
          ${{ matrix.test-cmd }}
